# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
PackageIdentifier: IanMiller.Islands
PackageVersion: 0.4.8
MinimumOSVersion: 10.0.17763.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: islands\build\islands.exe
    PortableCommandAlias: islands
Commands:
  - islands
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/ian-miller-gz/islands-packages/releases/download/0.4.8/islands-0.4.8-windows-x64.zip
    InstallerSha256: 10f28bce97be3a50c26d65dc970b2877483adc559a4e38a4c1cf778124df5326
ManifestType: installer
ManifestVersion: 1.12.0
