# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
PackageIdentifier: IanMiller.Islands
PackageVersion: 0.4.6
MinimumOSVersion: 10.0.17763.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: islands\build\Island.exe
    PortableCommandAlias: islands
Commands:
  - islands
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/ian-miller-gz/islands-packages/releases/download/0.4.6/islands-0.4.6-windows-x64.zip
    InstallerSha256: 5394cf4b8092fe18b644a1ca7cf2d0da8541f604a2c3d625b9502b78feb6c5e7
ManifestType: installer
ManifestVersion: 1.12.0
